//O var UI = {
var UI = {
    //O Stage: require('./Stage'),
    //Stage: require('./Stage'),
    //O Container: require('./Container'),
    //Container: require('./Container'),
    //O ScrollingContainer: require('./ScrollingContainer'),
    //ScrollingContainer: require('./ScrollingContainer'),
    //O SortableList: require('./SortableList'),
    //SortableList: require('./SortableList'),
    //O Sprite: require('./Sprite'),
    //Sprite: require('./Sprite'),
    //O TilingSprite: require('./TilingSprite'),
    //TilingSprite: require('./TilingSprite'),
    //O SliceSprite: require('./SliceSprite'),
    //SliceSprite: require('./SliceSprite'),
    //O Slider: require('./Slider'),
    //Slider: require('./Slider'),
    //O ScrollBar: require('./ScrollBar'),
    //ScrollBar: require('./ScrollBar'),
    //O Text: require('./Text'),
    //Text: require('./Text'),
    //O DynamicText: require('./DynamicText/DynamicText'),
    DynamicText: require('./DynamicText/DynamicText'),
    //O DynamicTextStyle: require('./DynamicText/DynamicTextStyle'),
    DynamicTextStyle: require('./DynamicText/DynamicTextStyle'),
    //O TextInput: require('./TextInput'),
    //TextInput: require('./TextInput'),
    //O Button: require('./Button'),
    //Button: require('./Button'),
    //O CheckBox: require('./CheckBox'),
    //CheckBox: require('./CheckBox'),
    //O Helpers: require('./Helpers'),
    Helpers: require('./Helpers'),
    //O Tween: require('./Tween'),
    Tween: require('./Tween'),
    //O Ease: require('./Ease/Ease'),
    Ease: require('./Ease/Ease'),
    //O Interaction: require('./Interaction/Interaction'),
    Interaction: require('./Interaction/Interaction'),
    //O Base: require('./UIBase'),
    Base: require('./UIBase'),
    //O Ticker: require('./Ticker').shared,
    //Ticker: require('./Ticker').shared,
};

//O module.exports = UI;
module.exports = UI;
